### ISSUE TITLE
Total de producción y mensaje 

### ISSUE THREAD

**Issue by zNahuelz** [zNahuelz/trinity_corp_soa#2]
- BUG: Al insertar registros de producción no muestra mensaje de completado y permite hacerlo 2 veces en un mismo día. (Al salir y entrar al formulario muestra mensaje de "ya ingreso datos correctamente" - OK). 
- NUEVO: Mostrar total de producción debajo del listado de cada sede. Vease: https://prnt.sc/jD8iA4_Va0FC

**Comment by clch2409** [comment]
Arreglado el issue, solamente hice cambios en la colocación del método de verificación de datos ingresados por el día
